apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: "awajid3/springboot_app:{{ .Values.image.tag }}" # 👈 Capital 'V' and clean spacing
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: "8081"
